---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-body-size: "900m"
  proxy-read-timeout: "900"
  proxy-connect-timeout: "900"
  proxy-send-timeout: "900"
